### ISSUE TITLE
TcpBase.cs错误

### ISSUE THREAD

**Issue by Charltsing** [autcn/SiS.Communcation#1]
SiS.Communcation/src/SiS.Communication/Tcp/TcpBase.cs 141行  
Message = null会导致 OnRawMessageReceived(rawMessage); 报错

运行到
https://github.com/autcn/SiS.Communcation/blob/master/src/SiS.Communication/Business/TcpModelClient.cs 第64行
tcpRawMessageArgs.Message is null

起因是TcpBase.cs 131行，clientRingBuffer.Buffer的前几个字节是00。

这个问题出在SimplePacketSpliter，如果发一个0字节的文本，SimplePacketSpliter会返回一个65536的0字节数组，导致接收端报错！

Contract.Requires(messageData != null && count > 0); 这句没效果，是不是需要啥插件？
sendBuffer.SetLength(4 + 0);  返回的65536
**************************************************

另外SiS.Communication/Business/RequestMessageBase.cs中，ID是不是应该 ID = Guid.NewGuid();

**Comment by autcn** [comment]
A zero length packet is not allowed to send, so I have added some parameter validations for sending functions.
As what you said, I have changed Contract.Required to Contract.Assert. It is working now.
Thank you for your feedback.

**Comment by Charltsing** [comment]
SiS.Communication/Business/RequestMessageBase.cs中，ID是不是应该 ID = Guid.NewGuid();

**Comment by autcn** [comment]
> SiS.Communication/Business/RequestMessageBase.cs中，ID是不是应该 ID = Guid.NewGuid();

Yes, it's a serious bug. I have fixed it in the version 1.3.6. Thank you very much!
